import {KEYBOARD_KEY} from './keyboardKeys';

export enum KEYBOARD_COMBINATION_EVENT {
  PASTE = 'Paste',
}

export type KEYBOARD_EVENT = KEYBOARD_COMBINATION_EVENT | KEYBOARD_KEY.TAB;
export const KEYBOARD_EVENT = {...KEYBOARD_COMBINATION_EVENT, [KEYBOARD_KEY.TAB]: KEYBOARD_KEY.TAB};
